#!/bin/bash
#declare array
fileNames=( 0-hello_world 2-hellofile 3-twofiles 4-lastlines 5-firstlines 6-third_line 8-cwd_state 9-duplicate_last_line 11-directories 12-newest_files 13-unique 14-findthatword 15-countthatword 16-whatsnext 17-hidethisword 18-letteronly 19-AZ 20-hiago 21-reverse 22-users_and_homes )
contents=('echo "Hello, World"' 'cat /etc/passwd' 'cat /etc/passwd /etc/hosts' 'tail /etc/passwd' 'head -10 /etc/passwd' 'head --lines=3 iacta | tail --lines=1' 'ls -la >> ls_cwd_content' 'tail --lines=1 iacta >> iacta' 'find . -type f -name "*.js" -delete' 'find . -type d -path "./*" -print | wc -l' 'ls -t | head' 'sort | uniq -u' 'grep -i "root" /etc/passwd' 'grep -c "bin" /etc/passwd' 'grep -iA 3 "root" /etc/passwd' 'grep -v "bin" /etc/passwd' 'grep "^[A-Za-z]" /etc/ssh/sshd_config' 'tr Ac Ze' 'tr -d cC' 'rev' 'cut -d":" -f1,6 /etc/passwd | sort')
arrayLength=${#fileNames[@]}
for (( i=0; i<${arrayLength}; i++ ));
do
   printf "#!/bin/bash\n%s${contents[$i]}" > ${fileNames[$i]}
   chmod u+x ${fileNames[$i]}
done
