#!/bin/bash                                                                      
#declare array                                                                   
fileNames=(
		0-hello_world
			2-hellofile
				3-twofiles
					4-lastlines
						5-firstlines
							6-third_line
								8-cwd_state
									9-duplicate_last_line
										10-no_more_js
											11-directories
												12-newest_files
													13-unique
														14-findthatword
															15-countthatword
																16-whatsnext
																	17-hidethisword
																		18-letteronly
																			19-AZ
																				20-hiago
																					21-reverse
																						22-users_and_homes
																		100-empty_casks
														101-gifs
										102-acrostic
						103-the_biggest_fan
		 )					
																						contents=(
																								'echo "Hello, World\n"'
																									'cat /etc/passwd\n'
																										'cat /etc/passwd /etc/hosts\n'
																											'tail /etc/passwd\n'
																												'head -10 /etc/passwd\n'
																													'head --lines=3 iacta | tail --lines=1\n'
																														'ls -la >> ls_cwd_content\n'
																															'tail --lines=1 iacta >> iacta\n'
																																'find . -type f -name "*.js" -delete\n'
																																	'find . -type d -path "./*" -print | wc -l\n'
																																		'ls -t | head\n'
																																			'sort | uniq -u\n'
																																				'grep -i "root" /etc/passwd\n'
																																					'grep -c "bin" /etc/passwd\n'
																																						'grep -iA 3 "root" /etc/passwd\n'
																																							'grep -v "bin" /etc/passwd\n'
																																								'grep "^[A-Za-z]" /etc/ssh/sshd_config\n'
																																									'tr Ac Ze\n'
																																										'tr -d cC\n'
																																											'rev\n'
																																												'cut -d":" -f1,6 /etc/passwd | sort\n'
																																												'find . -empty -printf %f"\n"\n'
																																													'find . -type f -name \*.gif -printf "%f\n" | LC_ALL=C sort -f | rev | cut -b 5- | rev\n'
																																														'cut -c 1 | paste -s -d ""\n'
																																															'tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d " " -f -1 | rev\n')                                                  
																																												arrayLength=${#fileNames[@]}                                                     
																																												for (( i=0; i<${arrayLength}; i++ ));                                            
																																												do                                                                               
																																													   printf "#!/bin/bash\n%s${contents[$i]}" > ${fileNames[$i]}                    
																																													      chmod u+x ${fileNames[$i]}                                                    
																																												      done 
